export const PATTERNS = [
  { name: "Two Pointers",         when: "Array/string problem requiring pair search. Works on sorted arrays or when left+right converge.", icon: "⇔" },
  { name: "Sliding Window",       when: "Contiguous subarray/substring with a constraint (max, min, exactly k). Avoid O(n²) nested loops.", icon: "▤" },
  { name: "Fast & Slow Pointers", when: "Cycle detection in linked list or array. Finding middle node. Floyd's algorithm.", icon: "⊳⊳" },
  { name: "Merge Intervals",      when: "Overlapping intervals. Requires sorting by start time first.", icon: "⊞" },
  { name: "Cyclic Sort",          when: "Array contains numbers in range [1, n]. Missing/duplicate number problems.", icon: "↻" },
  { name: "Linked List Reversal", when: "Reverse a linked list or a sub-list in-place. O(1) space.", icon: "⇋" },
  { name: "Tree BFS",             when: "Level-order traversal. Shortest path in unweighted tree. Uses a queue.", icon: "⊡" },
  { name: "Tree DFS",             when: "Path problems, subtree search, root-to-leaf. Uses recursion/stack.", icon: "⬇" },
  { name: "Two Heaps",            when: "Median of a stream. Partition elements into two halves (max-heap + min-heap).", icon: "⊓⊔" },
  { name: "Subsets/Backtracking", when: "Generate all permutations, combinations, or subsets. Exponential by nature.", icon: "⋱" },
  { name: "Binary Search",        when: "Sorted array or monotonic search space. Reduces O(n) to O(log n).", icon: "⌇" },
  { name: "Top K Elements",       when: "K largest/smallest/most frequent. Heap of size K is optimal.", icon: "⊤" },
  { name: "K-way Merge",          when: "Merge K sorted lists/arrays. Min-heap with one pointer per list.", icon: "⋈" },
  { name: "Dynamic Programming",  when: "Overlapping subproblems + optimal substructure. Count/optimize over choices.", icon: "▦" },
  { name: "Topological Sort",     when: "Dependency ordering. Course schedule, build order. Kahn's or DFS.", icon: "→" },
  { name: "Graph BFS/DFS",        when: "Connected components, shortest path, islands. Build adjacency list first.", icon: "◎" },
  { name: "Monotonic Stack",      when: "Next greater/smaller element. Largest rectangle. Stack stays sorted.", icon: "⫶" },
  { name: "Prefix Sum",           when: "Range sum queries. Subarray sum equals K. Pre-compute cumulative sums.", icon: "Σ" },
  { name: "Bit Manipulation",     when: "XOR tricks for duplicates/missing. Subset enumeration via bitmask.", icon: "⊕" },
  { name: "Greedy",               when: "Locally optimal choice leads to global optimum. Prove no backtracking needed.", icon: "★" },
];
